title: El Terreno Reverdecer
description: Permaculture VanDwelling
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reverdecer.annalisagross.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Anna Lisa Gross
author-image:   profile.jpg
author-job:     Permaculture VanDwelling in Mexico
author-email:   # Add your email for contant form.
author-twitter: annalisa144 # Add your twitter account
about-author:   Anna Lisa &#38; Phillip live in their van with three dogs and two cats (and uninvited rodents and bugs) in the mountains of central Mexico. This land lives as we live&#58; thirsty, hungry, in myriad relationship. We look forward to your ideas and support on this <a href="google.com">permaculture</a> adVanture.

# Social settings
social-twitter:   annalisa144
social-facebook:  annalisa.gross.5
social-github:    annalisa144
social-pinterest: 
social-instagram: annalisamexico
social-youtube:   indiana144
social-vk:   
social-linkedin:
rss: ""

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
#disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll/figure

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

future: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      date: "2099-01-01 00:00:00 -0500"
      image: ""
      tags: ""
      categories: ""
      layout: "post"

# Name of repository, for use with Staticman
repository: "annalisa144/reverdecer"

# Staticman comments (see staticman.yml for configuration).
staticman:
  branch: "master"
